# Generated by Django 5.1.6 on 2025-08-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aulas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('duracao', models.IntegerField()),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
