# Generated by Django 5.1.6 on 2025-08-09 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('duracao', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='aulas',
        ),
    ]
